# Module 2 - Supervised Learning - Logistic Regression

---

## Imports

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import seaborn as sb
import time
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
# import tensorflow as tf
# from tensorflow import keras
from sklearn.linear_model import LogisticRegression


%matplotlib inline
# print(tf.__version__)

---

## Load Data

In [2]:
state = 'GA'

current_dir = os.getcwd()
# print(current_dir)
load_dir = current_dir + '\\module1_data\\' + state
#print(load_dir)

# uncomment 1
# data = 'Xstate_f194.npy' #original
# data = 'Xforest_f102.npy' #random forest feature importance
data = 'Xpca_f194_c049_v9713.npy' #principle components

X = np.load(load_dir + '\\' + data)
print("x_shape: ", X.shape)
# print("==X==")
# print(X[:10])

y = np.load(load_dir + '\\ystate.npy')
y = y - 1
print("y_shape: ", y.shape)
# print("==y==")
# print(y[:10])

x_shape:  (83620, 49)
y_shape:  (83620, 1)


In [3]:
#DO NOT CHANGE

#split into training and test sets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, train_size=0.70, random_state=0, shuffle=True)

print('X train:', X_train.shape)
print('y train:', y_train.shape)
print('X test: ', X_test.shape)
print('y test: ', y_test.shape)

X train: (58533, 49)
y train: (58533, 1)
X test:  (25086, 49)
y test:  (25086, 1)


---

## Logistic Regression

### Setup

In [4]:
# create an instance and fit the model 
logmodel = LogisticRegression()
y_train1 = y_train.flatten()
# print("---Y-TRAIN SHAPE---")
# print(y_train1.shape)
logmodel.fit(X_train, y_train1)

# predictions
Predictions = logmodel.predict(X_test)
# print("---Predictions:---")
# print(Predictions[:10])

y_test1 = y_test.flatten()

# print("===Y TEST1:===")
# print(y_test1[:10])

print("===CLASSIFICATION REPORT===")
print(classification_report(y_test1,Predictions))

print("===CONFUSION MATRIX===")
print(confusion_matrix(y_test1, Predictions))

C:\Users\Roshni Ghosh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Roshni Ghosh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


===CLASSIFICATION REPORT===
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         9
           1       0.48      0.30      0.37     10401
           2       0.54      0.78      0.64     12669
           3       0.25      0.01      0.02      2007

    accuracy                           0.52     25086
   macro avg       0.32      0.27      0.26     25086
weighted avg       0.49      0.52      0.48     25086

===CONFUSION MATRIX===
[[   0    1    8    0]
 [   0 3138 7241   22]
 [   0 2697 9945   27]
 [   0  765 1226   16]]


C:\Users\Roshni Ghosh\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


### Test Set

In [5]:
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logmodel.score(X_test, y_test1)))
print("===Accuracy of Prediction:===")
print(np.sum(Predictions == y_test1), '/', y_test1.shape[0])

Accuracy of logistic regression classifier on test set: 0.52
===Accuracy of Prediction:===
13099 / 25086


### Save Model / Results

In [6]:
save_dir = current_dir + '\\module2_data\\' + state + '\\LogisticRegression'
print(save_dir)
if not os.path.exists(save_dir):
    os.makedirs(save_dir)

C:\Users\Roshni Ghosh\Documents\MachineLearning\traffic-accident-weather-analysis\code\module2_data\GA\LogisticRegression
